void LoadAssets() {
  FakePrecacheSound("*/kento_smashbros/sfx/5.mp3");
  FakePrecacheSound("*/kento_smashbros/sfx/4.mp3");
  AddFileToDownloadsTable("sound/kento_smashbros/sfx/5.mp3");
  AddFileToDownloadsTable("sound/kento_smashbros/sfx/4.mp3");
  AddFileToDownloadsTable("sound/kento_smashbros/sfx/3.mp3");
  AddFileToDownloadsTable("sound/kento_smashbros/sfx/2.mp3");
  AddFileToDownloadsTable("sound/kento_smashbros/sfx/1.mp3");
  AddFileToDownloadsTable("sound/kento_smashbros/sfx/go.mp3");
  AddFileToDownloadsTable("sound/kento_smashbros/sfx/timeup.mp3");
  AddFileToDownloadsTable("sound/kento_smashbros/sfx/gameset.mp3");
  AddFileToDownloadsTable("sound/kento_smashbros/sfx/blowaway_s.mp3");
  AddFileToDownloadsTable("sound/kento_smashbros/sfx/blowaway_m.mp3");
  AddFileToDownloadsTable("sound/kento_smashbros/sfx/blowaway_l.mp3");
  AddFileToDownloadsTable("sound/kento_smashbros/sfx/cheer_s.mp3");
  AddFileToDownloadsTable("sound/kento_smashbros/sfx/cheer_m.mp3");
  AddFileToDownloadsTable("sound/kento_smashbros/sfx/cheer_l.mp3");
  AddFileToDownloadsTable("sound/kento_smashbros/sfx/cheer_s.mp3");
  AddFileToDownloadsTable("sound/kento_smashbros/sfx/cheer_m.mp3");
  AddFileToDownloadsTable("sound/kento_smashbros/sfx/cheer_l.mp3");

  FakePrecacheSound("*/kento_smashbros/sfx/5.mp3");
  FakePrecacheSound("*/kento_smashbros/sfx/4.mp3");
  FakePrecacheSound("*/kento_smashbros/sfx/3.mp3");
  FakePrecacheSound("*/kento_smashbros/sfx/2.mp3");
  FakePrecacheSound("*/kento_smashbros/sfx/1.mp3");
  FakePrecacheSound("*/kento_smashbros/sfx/go.mp3");
  FakePrecacheSound("*/kento_smashbros/sfx/timeup.mp3");
  FakePrecacheSound("*/kento_smashbros/sfx/gameset.mp3");
  FakePrecacheSound("*/kento_smashbros/sfx/cheer_s.mp3");
  FakePrecacheSound("*/kento_smashbros/sfx/cheer_m.mp3");
  FakePrecacheSound("*/kento_smashbros/sfx/cheer_l.mp3");
  FakePrecacheSound("*/kento_smashbros/sfx/blowaway_s.mp3");
  FakePrecacheSound("*/kento_smashbros/sfx/blowaway_m.mp3");
  FakePrecacheSound("*/kento_smashbros/sfx/blowaway_l.mp3");
  FakePrecacheSound("*/kento_smashbros/sfx/cheer_s.mp3");
  FakePrecacheSound("*/kento_smashbros/sfx/cheer_m.mp3");
  FakePrecacheSound("*/kento_smashbros/sfx/cheer_l.mp3");

  AddFileToDownloadsTable("materials/kento_smashbros/freeze_3.vmt");
  AddFileToDownloadsTable("materials/kento_smashbros/freeze_3.vtf");
  AddFileToDownloadsTable("materials/kento_smashbros/freeze_2.vmt");
  AddFileToDownloadsTable("materials/kento_smashbros/freeze_2.vtf");
  AddFileToDownloadsTable("materials/kento_smashbros/freeze_1.vmt");
  AddFileToDownloadsTable("materials/kento_smashbros/freeze_1.vtf");
  AddFileToDownloadsTable("materials/kento_smashbros/go.vmt");
  AddFileToDownloadsTable("materials/kento_smashbros/go.vtf");
  AddFileToDownloadsTable("materials/kento_smashbros/time_5.vmt");
  AddFileToDownloadsTable("materials/kento_smashbros/time_5.vtf");
  AddFileToDownloadsTable("materials/kento_smashbros/time_4.vmt");
  AddFileToDownloadsTable("materials/kento_smashbros/time_4.vtf");
  AddFileToDownloadsTable("materials/kento_smashbros/time_3.vmt");
  AddFileToDownloadsTable("materials/kento_smashbros/time_3.vtf");
  AddFileToDownloadsTable("materials/kento_smashbros/time_2.vmt");
  AddFileToDownloadsTable("materials/kento_smashbros/time_2.vtf");
  AddFileToDownloadsTable("materials/kento_smashbros/time_1.vmt");
  AddFileToDownloadsTable("materials/kento_smashbros/time_1.vtf");
  AddFileToDownloadsTable("materials/kento_smashbros/timeup.vmt");
  AddFileToDownloadsTable("materials/kento_smashbros/timeup.vtf");
  AddFileToDownloadsTable("materials/kento_smashbros/gameset.vmt");
  AddFileToDownloadsTable("materials/kento_smashbros/gameset.vtf");

  PrecacheDecal("materials/kento_smashbros/freeze_3.vmt", true);
  PrecacheDecal("materials/kento_smashbros/freeze_3.vtf", true);
  PrecacheDecal("materials/kento_smashbros/freeze_2.vmt", true);
  PrecacheDecal("materials/kento_smashbros/freeze_2.vtf", true);
  PrecacheDecal("materials/kento_smashbros/freeze_1.vmt", true);
  PrecacheDecal("materials/kento_smashbros/freeze_1.vtf", true);
  PrecacheDecal("materials/kento_smashbros/go.vmt", true);
  PrecacheDecal("materials/kento_smashbros/go.vtf", true);
  PrecacheDecal("materials/kento_smashbros/time_5.vmt", true);
  PrecacheDecal("materials/kento_smashbros/time_5.vtf", true);
  PrecacheDecal("materials/kento_smashbros/time_4.vmt", true);
  PrecacheDecal("materials/kento_smashbros/time_4.vtf", true);
  PrecacheDecal("materials/kento_smashbros/time_3.vmt", true);
  PrecacheDecal("materials/kento_smashbros/time_3.vtf", true);
  PrecacheDecal("materials/kento_smashbros/time_2.vmt", true);
  PrecacheDecal("materials/kento_smashbros/time_2.vtf", true);
  PrecacheDecal("materials/kento_smashbros/time_1.vmt", true);
  PrecacheDecal("materials/kento_smashbros/time_1.vtf", true);
  PrecacheDecal("materials/kento_smashbros/timeup.vmt", true);
  PrecacheDecal("materials/kento_smashbros/timeup.vtf", true);
  PrecacheDecal("materials/kento_smashbros/gameset.vmt", true);
  PrecacheDecal("materials/kento_smashbros/gameset.vtf", true);
}